version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:mOSPKqoRfYlBvuvwrDsTcUKteynuGcWC@mongodb.railway.internal:27017
      - CORS_ORIGIN=mytoriasfront-production.up.railway.app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
