version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Mytorias
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: